function [] = mergeAndCompilePDFLatex_Comparison(obj)

sFile_TitlePage = 'titlePage_Comparison.tex';
sFile_Profile = 'Profile_Comparison.tex';
sFile_Graphic = 'graphic_Comparison.tex';
sFile_Graphic_Single = 'graphic.tex';
sFile_Part_Diagrams = 'diagrams_Comparison.tex';
sFile_Part_Overview = 'overview_Comparison.tex';
sFile_Details_Overview = 'detailsoverview.tex';
sFileOutput_tex = 'Profile.tex';

% Names of PDF files
cFileNames = {'01_Profile_Situations.pdf', ...
    '02_Profile_Situation_1.pdf', ...
    '03_Profile_Activity_Mean_1.pdf', ...
    '04_Profile_Activity_1.pdf', ...
    '05_Profile_Source_Mean_1.pdf', ...
    '06_Profile_Source_1.pdf', ...
    '07_Profile_Situation_2.pdf', ...
    '08_Profile_Activity_Mean_2.pdf', ...
    '09_Profile_Activity_2.pdf', ...
    '10_Profile_Source_Mean_2.pdf', ...
    '11_Profile_Source_2.pdf', ...
    '12_Profile_Situation_3.pdf', ...
    '13_Profile_Activity_Mean_3.pdf', ...
    '14_Profile_Activity_3.pdf', ...
    '15_Profile_Source_Mean_3.pdf', ...
    '16_Profile_Source_3.pdf', ...
    ['17_', obj.stSubject.Name, '.pdf']};

cCaptions = {['Personal Profile: ', obj.stSubject.Name], ...
    'Höranstrengung getrennt nach Situation', ...
    'Mittlere Höranstrengung getrennt nach Aktivität', ...
    'Höranstrengung getrennt nach Aktivität', ...
    'Mittlere Höranstrengung getrennt nach Signalquellen', ...
    'Höranstrengung getrennt nach Signalquellen', ...
    'Sprachverstehen getrennt nach Situation', ...
    'Mittleres Sprachverstehen getrennt nach Aktivität', ...
    'Sprachverstehen getennt nach Aktivität', ...
    'Mittleres Sprachverstehen getrennt nach Signalquellen', ...
    'Sprachverstehen getrennt nach Signalquellen', ...
    'Beeinträchtigung getrennt nach Situation', ...
    'Mittlere Beeinträchtigung getrennt nach Aktivität', ...
    'Beeinträchtigung getrennt nach Aktivität', ...
    'Mittlere Beeinträchtigung getrennt nach Signalquellen', ...
    'Beeinträchtigung getrennt nach Signalquellen', ...
    [obj.stSubject.Name, ' data availability EMA 1'], ...
    [obj.stSubject.Name, ' data availability EMA 2']};

% Read LaTeX data
sTitlePage = fileread(fullfile(obj.sFolder_Latex, sFile_TitlePage));
sProfile = fileread(fullfile(obj.sFolder_Latex, sFile_Profile));
sGraphics = fileread(fullfile(obj.sFolder_Latex, filesep, sFile_Graphic));
sGraphics_Overview = fileread(fullfile(obj.sFolder_Latex, filesep, sFile_Graphic_Single));

sPart_Diagrams = fileread(fullfile(obj.sFolder_Latex, sFile_Part_Diagrams));
sPart_Overview = fileread(fullfile(obj.sFolder_Latex, sFile_Part_Overview));
sDetails_Overview = fileread(fullfile(obj.sFolder_Latex, sFile_Details_Overview));

%% Exchange Diagrams


vRotation = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 0, 0, 0, 0, 0];
vWidth = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];

sDiagrams = '';

nDiagrams = 16;
for iDiagram = 1:nDiagrams

    sCurrentChart = strrep(sGraphics, '$filename1$', ...
        strrep([obj.stComparison(1).Folder, filesep, 'graphics', ...
        filesep, cFileNames{iDiagram}], '\', '/'));
    sCurrentChart = strrep(sCurrentChart, '$filename2$', ...
        strrep([obj.stComparison(2).Folder, filesep, 'graphics', ...
        filesep, cFileNames{iDiagram}], '\', '/'));
    sCurrentChart = strrep(sCurrentChart, '$caption$', ...
        cCaptions{iDiagram});
    sCurrentChart = strrep(sCurrentChart, '$rotation$', ...
        num2str(vRotation(iDiagram)));
    sCurrentChart = strrep(sCurrentChart, '$width$', ...
        num2str(vWidth(iDiagram)));
    
    sDiagrams = [sDiagrams, sCurrentChart];
    
end


%% Exchange Overview #1


sDetails_Overview_Complete_01 = '';

for iDay = 1:obj.stComparison(1).Analysis.NumberOfDays
   
    sDetails_Overview_Day = strrep(sDetails_Overview, ...
        '$daynumber$', num2str(iDay));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$date$', char(obj.stComparison(1).Analysis.Dates(iDay)));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$dauer$', secondsToTime(obj.stComparison(1).Analysis.TimePerDay(iDay)));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$numberofparts$', ...
        num2str(obj.stComparison(1).Analysis.NumberOfParts(iDay)));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$numberofquestionnaires$', ...
        num2str(obj.stComparison(1).Analysis.NumberOfQuestionnaires(iDay)));
    
    sDetails_Overview_Complete_01 = [sDetails_Overview_Complete_01, ...
        sDetails_Overview_Day];
    
end

sOverview_01 = strrep(sGraphics_Overview, '$filename$', ...
        strrep([obj.stComparison(1).Folder, filesep, 'graphics', ...
        filesep, cFileNames{17}], '\', '/'));
sOverview_01 = strrep(sOverview_01, '$caption$', cCaptions{17});

% Overview is displayed in portrait mode
nRotation = 0;
sOverview_01 = strrep(sOverview_01, '$rotation$', num2str(nRotation));
sWidth = '1.15';
sOverview_01 = strrep(sOverview_01, '$width$', sWidth);


%% Exchange Overview #2


sDetails_Overview_Complete_02 = '';

for iDay = 1:obj.stComparison(2).Analysis.NumberOfDays
   
    sDetails_Overview_Day = strrep(sDetails_Overview, ...
        '$daynumber$', num2str(iDay));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$date$', char(obj.stComparison(2).Analysis.Dates(iDay)));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$dauer$', secondsToTime(obj.stComparison(2).Analysis.TimePerDay(iDay)));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$numberofparts$', ...
        num2str(obj.stComparison(2).Analysis.NumberOfParts(iDay)));
    sDetails_Overview_Day = strrep(sDetails_Overview_Day, ...
        '$numberofquestionnaires$', ...
        num2str(obj.stComparison(2).Analysis.NumberOfQuestionnaires(iDay)));
    
    sDetails_Overview_Complete_02 = [sDetails_Overview_Complete_02, ...
        sDetails_Overview_Day];
    
end

sOverview_02 = strrep(sGraphics_Overview, '$filename$', ...
        strrep([obj.stComparison(2).Folder, filesep, 'graphics', ...
        filesep, cFileNames{17}], '\', '/'));
sOverview_02 = strrep(sOverview_02, '$caption$', cCaptions{18});

% Overview is displayed in portrait mode
nRotation = 0;
sOverview_02 = strrep(sOverview_02, '$rotation$', num2str(nRotation));
sWidth = '1.15';
sOverview_02 = strrep(sOverview_02, '$width$', sWidth);


%% Adjust general information


% Replace Information on titlepage
sTitlePage = strrep(sTitlePage, '$termProfile$', obj.stLaTeXCommands.termProfile);
sTitlePage = strrep(sTitlePage, '$termComparison$', obj.stLaTeXCommands.termComparison);
sTitlePage = strrep(sTitlePage, '$termSubject$', obj.stLaTeXCommands.termSubject);
sTitlePage = strrep(sTitlePage, '$subject$', obj.stSubject.Name);
sTitlePage = strrep(sTitlePage, '$termUpdated$', obj.stLaTeXCommands.termUpdated);
sTitlePage = strrep(sTitlePage, '$termComments$', obj.stLaTeXCommands.termComments);
sTitlePage = strrep(sTitlePage, '$appendix$', ...
    strrep(obj.stSubject.Appendix, '_', ' '));
sTitlePage = strrep(sTitlePage, '$latexfolder$', ...
    strrep(obj.sFolder_Latex, '\', '/'));

% Insert Footer
sProfile = strrep(sProfile, '$headtext_left$', ['Vergleich: ', ...
    obj.stSubject.Name]);
sProfile = strrep(sProfile, '$headtext_center$', 'Stand:');
sProfile = strrep(sProfile, '$headtext_right$', obj.stLaTeXCommands.termInstitute);
sProfile = strrep(sProfile, '$foottext_left$', '');
sProfile = strrep(sProfile, '$foottext_center$', '');
sProfile = strrep(sProfile, '$foottext_right$', 'Seite');

% Replace Part Page variables
sPart_Diagrams = strrep(sPart_Diagrams, '$numberofquestionnaires$', ...
    num2str(sum(obj.stComparison(1).Analysis.NumberOfQuestionnaires) +...
    sum(obj.stComparison(2).Analysis.NumberOfQuestionnaires)));

sPart_Overview_01 = strrep(sPart_Overview, '$durchlauf$', ...
    num2str(1));
sPart_Overview_01 = strrep(sPart_Overview_01, '$numberofdays$', ...
    num2str(obj.stComparison(1).Analysis.NumberOfDays));
sPart_Overview_01 = strrep(sPart_Overview_01, '$numberofparts$', ...
    num2str(sum(obj.stComparison(1).Analysis.NumberOfParts)));
sPart_Overview_01 = strrep(sPart_Overview_01, '$numberofquestionnaires$', ...
    num2str(sum(obj.stComparison(1).Analysis.NumberOfQuestionnaires)));
sPart_Overview_01 = strrep(sPart_Overview_01, '$detailsoverview$', ...
    sDetails_Overview_Complete_01);

sPart_Overview_02 = strrep(sPart_Overview, '$durchlauf$', ...
    num2str(2));
sPart_Overview_02 = strrep(sPart_Overview_02, '$numberofdays$', ...
    num2str(obj.stComparison(2).Analysis.NumberOfDays));
sPart_Overview_02 = strrep(sPart_Overview_02, '$numberofparts$', ...
    num2str(sum(obj.stComparison(2).Analysis.NumberOfParts)));
sPart_Overview_02 = strrep(sPart_Overview_02, '$numberofquestionnaires$', ...
    num2str(sum(obj.stComparison(2).Analysis.NumberOfQuestionnaires)));
sPart_Overview_02 = strrep(sPart_Overview_02, '$detailsoverview$', ...
    sDetails_Overview_Complete_02);


%% Merge all LaTeX data together


sProfile = strrep(sProfile, '$titlePage$', sTitlePage);
sProfile = strrep(sProfile, '$part_diagrams$', sPart_Diagrams);
sProfile = strrep(sProfile, '$contents_diagrams$', sDiagrams);
sProfile = strrep(sProfile, '$part_overview_1$', sPart_Overview_01);
sProfile = strrep(sProfile, '$contents_overview_1$', sOverview_01);
sProfile = strrep(sProfile, '$part_overview_2$', sPart_Overview_02);
sProfile = strrep(sProfile, '$contents_overview_2$', sOverview_02);

hFid_Profile = fopen([obj.stSubject.Folder, filesep, 'graphics', ...
    filesep, sFileOutput_tex], 'w');
fwrite(hFid_Profile, sProfile);
fclose(hFid_Profile);


%% Compile and tidy up

   
% Compile PDF file TWICE because LaTeX
system(['pdflatex -shell-escape --src -interaction=nonstopmode ', ...
    obj.stSubject.Folder, filesep, 'graphics', filesep, sFileOutput_tex]);

system(['pdflatex -shell-escape --src -interaction=nonstopmode ', ...
    obj.stSubject.Folder, filesep, 'graphics', filesep, sFileOutput_tex]);

% Delete additional output
delete([obj.sFolderMain, filesep, 'profile.lof']);
delete([obj.sFolderMain, filesep, 'profile.log']);
delete([obj.sFolderMain, filesep, 'profile.aux']);

end
