ActivityDescription = {'Relaxing','Eating','Kitchen work',...
    'Reading-Computer', 'Music listening', 'Chores' , ...
    'Yard-Balcony' , 'Car driving' , 'Car ride' , ...
    'Bus' , 'Train', 'By foot', 'By bike', ...
    'On visit', 'Party' ,'Restaurant', 'Theater etc', ...
    'Meeting' , 'Admin or med office' , 'Store', ...
    'Office' , 'Workshop' , 'Counter', 'Meeting room', ...
    'Working outside', 'Cantine', 'Other activity'}; 